Repository kubernetes-csi/csi-lib-utils, pull requests merged in 2019-04, with the labels that each got.

#24 discover in cluster namespace for leader election
  leaderelection/leader_election.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#25 remove builder pattern for leader election due to unexported struct
  leaderelection/leader_election.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#26 Prow testing
  .prow.sh
  release-tools/.prow.sh
  release-tools/README.md
  release-tools/build.make
  release-tools/filter-junit.go
  release-tools/prow.sh
  release-tools/travis.yml
  release-tools/util.sh
  release-tools/verify-shellcheck.sh
  release-tools/verify-subtree.sh
  rpc/common_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#27 Prow testing: update csi-release-tools
  release-tools/prow.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#29 Add PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/M

#28 update to Go 1.12.4
  release-tools/travis.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS
