Repository kubernetes-csi/csi-lib-utils, pull requests merged in 2020-11, with the labels that each got.

#65 Prepare release v0.9.0
  CHANGELOG/CHANGELOG-0.9.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/S

#67 metrics: optional process_start_time
  metrics/metrics.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/M

#68 Workaround for process start time metric not show up
  metrics/metrics.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note-none, size/XS

#70 Add health checker to leader election library
  leaderelection/leader_election.go
  metrics/metrics.go
  metrics/metrics_test.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/L

#72 Update release notes for v0.9.0
  CHANGELOG/CHANGELOG-0.9.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/S

#71 Update release-tools
  release-tools/prow.sh
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/XS

#73 Update release tools
  release-tools/prow.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/M
